/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package enums

import (
	"encoding/json"
	"errors"
	"fmt"
)

type SalmonWeaponScheduleEnum string

// List of SalmonWeaponScheduleEnum
const (
	RandomGrizzcoSchedule      SalmonWeaponScheduleEnum = "Random Grizzco"
	RandomSchedule             SalmonWeaponScheduleEnum = "Random"
	SplooshOMaticSchedule      SalmonWeaponScheduleEnum = "Sploosh-o-matic"
	SplattershotJrSchedule     SalmonWeaponScheduleEnum = "Splattershot Jr."
	SplashOMaticSchedule       SalmonWeaponScheduleEnum = "Splash-o-matic"
	AerosprayMgSchedule        SalmonWeaponScheduleEnum = "Aerospray MG"
	SplattershotSchedule       SalmonWeaponScheduleEnum = "Splattershot"
	Point52GalSchedule         SalmonWeaponScheduleEnum = ".52 Gal"
	NZap85Schedule             SalmonWeaponScheduleEnum = "N-ZAP '85"
	SplattershotProSchedule    SalmonWeaponScheduleEnum = "Splattershot Pro"
	Point96GalSchedule         SalmonWeaponScheduleEnum = ".96 Gal"
	JetSquelcherSchedule       SalmonWeaponScheduleEnum = "Jet Squelcher"
	LunaBlasterSchedule        SalmonWeaponScheduleEnum = "Luna Blaster"
	BlasterSchedule            SalmonWeaponScheduleEnum = "Blaster"
	RangeBlasterSchedule       SalmonWeaponScheduleEnum = "Range Blaster"
	ClashBlasterSchedule       SalmonWeaponScheduleEnum = "Clash Blaster"
	RapidBlasterSchedule       SalmonWeaponScheduleEnum = "Rapid Blaster"
	RapidBlasterProSchedule    SalmonWeaponScheduleEnum = "Rapid Blaster Pro"
	L3NozzlenoseSchedule       SalmonWeaponScheduleEnum = "L-3 Nozzlenose"
	H3NozzlenoseSchedule       SalmonWeaponScheduleEnum = "H-3 Nozzlenose"
	SqueezerSchedule           SalmonWeaponScheduleEnum = "Squeezer"
	CarbonRollerSchedule       SalmonWeaponScheduleEnum = "Carbon Roller"
	SplatRollerSchedule        SalmonWeaponScheduleEnum = "Splat Roller"
	DynamoRollerSchedule       SalmonWeaponScheduleEnum = "Dynamo Roller"
	FlingzaRollerSchedule      SalmonWeaponScheduleEnum = "Flingza Roller"
	InkbrushSchedule           SalmonWeaponScheduleEnum = "Inkbrush"
	OctobrushSchedule          SalmonWeaponScheduleEnum = "Octobrush"
	ClassicSquifferSchedule    SalmonWeaponScheduleEnum = "Classic Squiffer"
	SplatChargerSchedule       SalmonWeaponScheduleEnum = "Splat Charger"
	SplatterscopeSchedule      SalmonWeaponScheduleEnum = "Splatterscope"
	ELiter4KSchedule           SalmonWeaponScheduleEnum = "E-liter 4K"
	ELiter4KScopeSchedule      SalmonWeaponScheduleEnum = "E-liter 4K Scope"
	Bamboozler14MkISchedule    SalmonWeaponScheduleEnum = "Bamboozler 14 Mk I"
	GooTuberSchedule           SalmonWeaponScheduleEnum = "Goo Tuber"
	SlosherSchedule            SalmonWeaponScheduleEnum = "Slosher"
	SodaSlosherSchedule        SalmonWeaponScheduleEnum = "Soda Slosher"
	TriSlosherSchedule         SalmonWeaponScheduleEnum = "Tri-Slosher"
	SloshingMachineSchedule    SalmonWeaponScheduleEnum = "Sloshing Machine"
	BloblobberSchedule         SalmonWeaponScheduleEnum = "Bloblobber"
	ExplosherSchedule          SalmonWeaponScheduleEnum = "Explosher"
	MiniSplatlingSchedule      SalmonWeaponScheduleEnum = "Mini Splatling"
	HeavySplatlingSchedule     SalmonWeaponScheduleEnum = "Heavy Splatling"
	HydraSplatlingSchedule     SalmonWeaponScheduleEnum = "Hydra Splatling"
	BallpointSplatlingSchedule SalmonWeaponScheduleEnum = "Ballpoint Splatling"
	Nautilus47Schedule         SalmonWeaponScheduleEnum = "Nautilus 47"
	DappleDualiesSchedule      SalmonWeaponScheduleEnum = "Dapple Dualies"
	SplatDualiesSchedule       SalmonWeaponScheduleEnum = "Splat Dualies"
	GloogaDualiesSchedule      SalmonWeaponScheduleEnum = "Glooga Dualies"
	DualieSquelchersSchedule   SalmonWeaponScheduleEnum = "Dualie Squelchers"
	DarkTetraDualiesSchedule   SalmonWeaponScheduleEnum = "Dark Tetra Dualies"
	SplatBrellaSchedule        SalmonWeaponScheduleEnum = "Splat Brella"
	TentaBrellaSchedule        SalmonWeaponScheduleEnum = "Tenta Brella"
	UndercoverBrellaSchedule   SalmonWeaponScheduleEnum = "Undercover Brella"
)

func (swse *SalmonWeaponScheduleEnum) UnmarshalJSON(b []byte) error {
	// Define a secondary type to avoid ending up with a recursive call to json.Unmarshal
	type SWSE SalmonWeaponScheduleEnum
	r := (*SWSE)(swse)
	err := json.Unmarshal(b, &r)
	if err != nil {
		panic(err)
	}
	switch *swse {
	case RandomGrizzcoSchedule, RandomSchedule, SplooshOMaticSchedule, SplattershotJrSchedule, SplashOMaticSchedule,
		AerosprayMgSchedule, SplattershotSchedule, Point52GalSchedule, NZap85Schedule, SplattershotProSchedule,
		Point96GalSchedule, JetSquelcherSchedule, LunaBlasterSchedule, BlasterSchedule, RangeBlasterSchedule,
		ClashBlasterSchedule, RapidBlasterSchedule, RapidBlasterProSchedule, L3NozzlenoseSchedule, H3NozzlenoseSchedule,
		SqueezerSchedule, CarbonRollerSchedule, SplatRollerSchedule, DynamoRollerSchedule, FlingzaRollerSchedule,
		InkbrushSchedule, OctobrushSchedule, ClassicSquifferSchedule, SplatChargerSchedule, SplatterscopeSchedule,
		ELiter4KSchedule, ELiter4KScopeSchedule, Bamboozler14MkISchedule, GooTuberSchedule, SlosherSchedule,
		SodaSlosherSchedule, TriSlosherSchedule, SloshingMachineSchedule, BloblobberSchedule, ExplosherSchedule,
		MiniSplatlingSchedule, HeavySplatlingSchedule, HydraSplatlingSchedule, BallpointSplatlingSchedule,
		Nautilus47Schedule, DappleDualiesSchedule, SplatDualiesSchedule, GloogaDualiesSchedule,
		DualieSquelchersSchedule, DarkTetraDualiesSchedule, SplatBrellaSchedule, TentaBrellaSchedule,
		UndercoverBrellaSchedule:
		return nil
	}
	return errors.New("Invalid enums.SalmonWeaponScheduleEnum. Got: " + fmt.Sprint(*swse))
}

type SalmonWeaponScheduleSpecialEnum string

const (
	RandomGrizzcoSpecialSchedule SalmonWeaponScheduleSpecialEnum = "Random Grizzco"
	RandomSpecialSchedule        SalmonWeaponScheduleSpecialEnum = "Random"
)

func (swsse *SalmonWeaponScheduleSpecialEnum) UnmarshalJSON(b []byte) error {
	// Define a secondary type to avoid ending up with a recursive call to json.Unmarshal
	type SWSSE SalmonWeaponScheduleSpecialEnum
	r := (*SWSSE)(swsse)
	err := json.Unmarshal(b, &r)
	if err != nil {
		panic(err)
	}
	switch *swsse {
	case RandomGrizzcoSpecialSchedule, RandomSpecialSchedule:
		return nil
	}
	return errors.New("Invalid enums.SalmonWeaponScheduleSpecialEnum. Got: " + fmt.Sprint(*swsse))
}
