/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type StatInkProfile struct {
	Nnid *interface{} `json:"nnid,omitempty"`

	FriendCode string `json:"friend_code,omitempty"`

	Twitter *interface{} `json:"twitter,omitempty"`

	Ikanakama *interface{} `json:"ikanakama,omitempty"`

	Ikanakama2 *interface{} `json:"ikanakama2,omitempty"`

	Environment *interface{} `json:"environment,omitempty"`
}
