/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type StatInkRulesSub struct {
	RankPeak string `json:"rank_peak,omitempty"`

	RankCurrent string `json:"rank_current,omitempty"`

	XPowerPeak *interface{} `json:"x_power_peak,omitempty"`

	XPowerCurrent *interface{} `json:"x_power_current,omitempty"`
}
