/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type Wave struct {
	WaterLevel *SplatnetDouble `json:"water_level,omitempty"`

	EventType *SplatnetDouble `json:"event_type,omitempty"`

	GoldenIkuraNum int32 `json:"golden_ikura_num,omitempty"`

	GoldenIkuraPopNum int32 `json:"golden_ikura_pop_num,omitempty"`

	IkuraNum int32 `json:"ikura_num,omitempty"`

	QuotaNum int32 `json:"quota_num,omitempty"`
}
