/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type Grade struct {
	Id string `json:"id,omitempty"`

	ShortName string `json:"short_name,omitempty"`

	LongName string `json:"long_name,omitempty"`

	Name string `json:"name,omitempty"`
}
