/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type StatInkShiftPlayer struct {
	SplatnetId string `json:"splatnet_id,omitempty"`

	Name string `json:"name,omitempty"`

	Special *StatInkTriple `json:"special,omitempty"`

	Rescue int32 `json:"rescue,omitempty"`

	Death int32 `json:"death,omitempty"`

	GoldenEggDelivered int32 `json:"golden_egg_delivered,omitempty"`

	PowerEggCollected int32 `json:"power_egg_collected,omitempty"`

	Species *StatInkKeyName `json:"species,omitempty"`

	Gender *StatInkGender `json:"gender,omitempty"`

	SpecialUses []int32 `json:"special_uses,omitempty"`

	Weapons []StatInkTriple `json:"weapons,omitempty"`

	BossKills []StatInkBossData `json:"boss_kills,omitempty"`
}
