/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type Player struct {
	HeadSkills *Skills `json:"head_skills,omitempty"`

	ShoesSkills *Skills `json:"shoes_skills,omitempty"`

	ClothesSkills *Skills `json:"clothes_skills,omitempty"`

	PlayerRank int32 `json:"player_rank,omitempty"`

	StarRank int32 `json:"star_rank,omitempty"`

	Nickname string `json:"nickname,omitempty"`

	PlayerType *PlayerType `json:"player_type,omitempty"`

	PrincipalId string `json:"principal_id,omitempty"`

	Head *Clothing `json:"head,omitempty"`

	Clothes *Clothing `json:"clothes,omitempty"`

	Shoes *Clothing `json:"shoes,omitempty"`

	Udemae *Udemae `json:"udemae,omitempty"`

	Weapon *Weapon `json:"weapon,omitempty"`
}
