/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type BattleStatInkJson struct {
	Id                             int               `json:"id,omitempty"`
	SplatnetNumber                 int               `json:"splatnet_number,omitempty"`
	Url                            string            `json:"url,omitempty"`
	User                           StatInkUser       `json:"user,omitempty"`
	Lobby                          StatInkKeyName    `json:"lobby,omitempty"`
	Mode                           StatInkKeyName    `json:"mode,omitempty"`
	Rule                           StatInkKeyName    `json:"rule,omitempty"`
	Map                            StatInkMap        `json:"map,omitempty"`
	Weapon                         StatInkWeapon     `json:"weapon,omitempty"`
	Freshness                      *StatInkFreshness `json:"freshness,omitempty"`
	Rank                           *StatInkRank      `json:"rank,omitempty"`
	RankExp                        *int              `json:"rank_exp,omitempty"`
	RankAfter                      *StatInkRank      `json:"rank_after,omitempty"`
	XPower                         *interface{}      `json:"x_power,omitempty"`
	XPowerAfter                    *interface{}      `json:"x_power_after,omitempty"`
	EstimateXPower                 *interface{}      `json:"estimate_x_power,omitempty"`
	Level                          int               `json:"level,omitempty"`
	LevelAfter                     int               `json:"level_after,omitempty"`
	StarRank                       int               `json:"star_rank,omitempty"`
	Result                         string            `json:"result,omitempty"`
	KnockOut                       bool              `json:"knock_out,omitempty"`
	RankInTeam                     int               `json:"rank_in_team,omitempty"`
	Kill                           int               `json:"kill,omitempty"`
	Death                          int               `json:"death,omitempty"`
	KillOrAssist                   int               `json:"kill_or_assist,omitempty"`
	Special                        int               `json:"special,omitempty"`
	KillRatio                      float64           `json:"kill_ratio,omitempty"`
	KillRate                       float64           `json:"kill_rate,omitempty"`
	MaxKillCombo                   *interface{}      `json:"max_kill_combo,omitempty"`
	MaxKillStreak                  *interface{}      `json:"max_kill_streak,omitempty"`
	DeathReasons                   *interface{}      `json:"death_reasons,omitempty"`
	MyPoint                        int               `json:"my_point,omitempty"`
	EstimateGachiPower             int               `json:"estimate_gachi_power,omitempty"`
	LeaguePoint                    string            `json:"league_point,omitempty"`
	MyTeamEstimateLeaguePoint      int               `json:"my_team_estimate_league_point,omitempty"`
	HisTeamEstimateLeaguePoint     int               `json:"his_team_estimate_league_point,omitempty"`
	MyTeamPoint                    *interface{}      `json:"my_team_point,omitempty"`
	HisTeamPoint                   *interface{}      `json:"his_team_point,omitempty"`
	MyTeamPercent                  string            `json:"my_team_percent,omitempty"`
	HisTeamPercent                 string            `json:"his_team_percent,omitempty"`
	MyTeamId                       string            `json:"my_team_id,omitempty"`
	HisTeamId                      string            `json:"his_team_id,omitempty"`
	Species                        StatInkKeyName    `json:"species,omitempty"`
	Gender                         StatInkGender     `json:"gender,omitempty"`
	FestTitle                      *StatInkKeyName   `json:"fest_title,omitempty"`
	FestExp                        *int              `json:"fest_exp,omitempty"`
	FestTitleAfter                 *StatInkKeyName   `json:"fest_title_after,omitempty"`
	FestExpAfter                   *int              `json:"fest_exp_after,omitempty"`
	FestPower                      *string           `json:"fest_power,omitempty"`
	MyTeamEstimateFestPower        *int              `json:"my_team_estimate_fest_power,omitempty"`
	HisTeamMyTeamEstimateFestPower *int              `json:"his_team_my_team_estimate_fest_power,omitempty"`
	MyTeamFestTheme                *string           `json:"my_team_fest_theme,omitempty"`
	MyTeamNickname                 *string           `json:"my_team_nickname,omitempty"`
	HisTeamNickname                *string           `json:"his_team_nickname,omitempty"`
	Clout                          *int              `json:"clout,omitempty"`
	TotalClout                     *int              `json:"total_clout,omitempty"`
	TotalCloutAfter                *int              `json:"total_clout_after,omitempty"`
	MyTeamWinStreak                *int              `json:"my_team_win_streak,omitempty"`
	HisTeamWinStreak               *int              `json:"his_team_win_streak,omitempty"`
	SynergyBonus                   *float64          `json:"synergy_bonus,omitempty"`
	SpecialBattle                  *StatInkKeyName   `json:"special_battle,omitempty"`
	ImageResult                    string            `json:"image_result,omitempty"`
	ImageGear                      string            `json:"image_gear,omitempty"`
	Gears                          StatInkGears      `json:"gears,omitempty"`
	Period                         int               `json:"period,omitempty"`
	PeriodRange                    string            `json:"period_range,omitempty"`
	Players                        []StatInkPlayer   `json:"players,omitempty"`
	Events                         *interface{}      `json:"events,omitempty"`
	SplatnetJson                   *interface{}      `json:"splatnet_json,omitempty"`
	Agent                          StatInkAgent      `json:"agent,omitempty"`
	Automated                      bool              `json:"automated,omitempty"`
	Environment                    *interface{}      `json:"environment,omitempty"`
	LinkUrl                        string            `json:"link_url,omitempty"`
	Note                           *interface{}      `json:"note,omitempty"`
	GameVersion                    string            `json:"game_version,omitempty"`
	NawabariBonus                  int               `json:"nawabari_bonus,omitempty"`
	StartAt                        StatInkTime       `json:"start_at,omitempty"`
	EndAt                          StatInkTime       `json:"end_at,omitempty"`
	RegisterAt                     StatInkTime       `json:"register_at,omitempty"`
}
