/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type salmonWeaponEnum string

// List of salmonWeaponEnum
const (
	SPLOOSH_O_MATIC     salmonWeaponEnum = "Sploosh-o-matic"
	SPLATTERSHOT_JR     salmonWeaponEnum = "Splattershot Jr."
	SPLASH_O_MATIC      salmonWeaponEnum = "Splash-o-matic"
	AEROSPRAY_MG        salmonWeaponEnum = "Aerospray MG"
	SPLATTERSHOT        salmonWeaponEnum = "Splattershot"
	five2GAL_           salmonWeaponEnum = ".52 Gal"
	N_ZAP_85            salmonWeaponEnum = "N-ZAP '85"
	SPLATTERSHOT_PRO    salmonWeaponEnum = "Splattershot Pro"
	nine6GAL_           salmonWeaponEnum = ".96 Gal"
	JET_SQUELCHER       salmonWeaponEnum = "Jet Squelcher"
	LUNA_BLASTER        salmonWeaponEnum = "Luna Blaster"
	BLASTER             salmonWeaponEnum = "Blaster"
	RANGE_BLASTER       salmonWeaponEnum = "Range Blaster"
	CLASH_BLASTER       salmonWeaponEnum = "Clash Blaster"
	RAPID_BLASTER       salmonWeaponEnum = "Rapid Blaster"
	RAPID_BLASTER_PRO   salmonWeaponEnum = "Rapid Blaster Pro"
	L_3_NOZZLENOSE      salmonWeaponEnum = "L-3 Nozzlenose"
	H_3_NOZZLENOSE      salmonWeaponEnum = "H-3 Nozzlenose"
	SQUEEZER            salmonWeaponEnum = "Squeezer"
	CARBON_ROLLER       salmonWeaponEnum = "Carbon Roller"
	SPLAT_ROLLER        salmonWeaponEnum = "Splat Roller"
	DYNAMO_ROLLER       salmonWeaponEnum = "Dynamo Roller"
	FLINGZA_ROLLER      salmonWeaponEnum = "Flingza Roller"
	INKBRUSH            salmonWeaponEnum = "Inkbrush"
	OCTOBRUSH           salmonWeaponEnum = "Octobrush"
	CLASSIC_SQUIFFER    salmonWeaponEnum = "Classic Squiffer"
	SPLAT_CHARGER       salmonWeaponEnum = "Splat Charger"
	SPLATTERSCOPE       salmonWeaponEnum = "Splatterscope"
	E_LITER_4_K         salmonWeaponEnum = "E-liter 4K"
	E_LITER_4_K_SCOPE   salmonWeaponEnum = "E-liter 4K Scope"
	BAMBOOZLER_14_MK_I  salmonWeaponEnum = "Bamboozler 14 Mk I"
	GOO_TUBER           salmonWeaponEnum = "Goo Tuber"
	SLOSHER             salmonWeaponEnum = "Slosher"
	SODA_SLOSHER        salmonWeaponEnum = "Soda Slosher"
	TRI_SLOSHER         salmonWeaponEnum = "Tri-Slosher"
	SLOSHING_MACHINE    salmonWeaponEnum = "Sloshing Machine"
	BLOBLOBBER          salmonWeaponEnum = "Bloblobber"
	EXPLOSHER           salmonWeaponEnum = "Explosher"
	MINI_SPLATLING      salmonWeaponEnum = "Mini Splatling"
	HEAVY_SPLATLING     salmonWeaponEnum = "Heavy Splatling"
	HYDRA_SPLATLING     salmonWeaponEnum = "Hydra Splatling"
	BALLPOINT_SPLATLING salmonWeaponEnum = "Ballpoint Splatling"
	NAUTILUS_47         salmonWeaponEnum = "Nautilus 47"
	DAPPLE_DUALIES      salmonWeaponEnum = "Dapple Dualies"
	SPLAT_DUALIES       salmonWeaponEnum = "Splat Dualies"
	GLOOGA_DUALIES      salmonWeaponEnum = "Glooga Dualies"
	DUALIE_SQUELCHERS   salmonWeaponEnum = "Dualie Squelchers"
	DARK_TETRA_DUALIES  salmonWeaponEnum = "Dark Tetra Dualies"
	SPLAT_BRELLA        salmonWeaponEnum = "Splat Brella"
	TENTA_BRELLA        salmonWeaponEnum = "Tenta Brella"
	UNDERCOVER_BRELLA   salmonWeaponEnum = "Undercover Brella"
	GRIZZCO_BLASTER     salmonWeaponEnum = "Grizzco Blaster"
	GRIZZCO_BRELLA      salmonWeaponEnum = "Grizzco Brella"
	GRIZZCO_CHARGER     salmonWeaponEnum = "Grizzco Charger"
	GRIZZCO_SLOSHER     salmonWeaponEnum = "Grizzco Slosher"
)
