/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type StatInkWave struct {
	KnownOccurrence *StatInkTriple `json:"known_occurrence,omitempty"`

	WaterLevel *StatInkTriple `json:"water_level,omitempty"`

	GoldenEggQuota int32 `json:"golden_egg_quota,omitempty"`

	GoldenEggAppearances int32 `json:"golden_egg_appearances,omitempty"`

	GoldenEggDelivered int32 `json:"golden_egg_delivered,omitempty"`

	PowerEggCollected int32 `json:"power_egg_collected,omitempty"`
}
