/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type StatInkShift struct {
	Id int32 `json:"id,omitempty"`

	Uuid string `json:"uuid,omitempty"`

	SplatnetNumber int32 `json:"splatnet_number,omitempty"`

	Url string `json:"url,omitempty"`

	ApiEndpoint string `json:"api_endpoint,omitempty"`

	User *StatInkShiftUser `json:"user,omitempty"`

	Stage *StatInkTriple `json:"stage,omitempty"`

	IsCleared bool `json:"is_cleared,omitempty"`

	FailReason *StatInkKeyName `json:"fail_reason,omitempty"`

	ClearWaves int32 `json:"clear_waves,omitempty"`

	DangerRate string `json:"danger_rate,omitempty"`

	Quota []int32 `json:"quota,omitempty"`

	Title *StatInkTitle `json:"title,omitempty"`

	TitleExp int32 `json:"title_exp,omitempty"`

	TitleAfter *StatInkTitle `json:"title_after,omitempty"`

	TitleExpAfter int32 `json:"title_exp_after,omitempty"`

	BossAppearances []StatInkBossData `json:"boss_appearances,omitempty"`

	Waves []StatInkWave `json:"waves,omitempty"`

	MyData *StatInkShiftPlayer `json:"my_data,omitempty"`

	Teammates []StatInkShiftPlayer `json:"teammates,omitempty"`

	Agent *StatInkSalmonAgent `json:"agent,omitempty"`

	Automated bool `json:"automated,omitempty"`

	Note *interface{} `json:"note,omitempty"`

	LinkUrl *interface{} `json:"link_url,omitempty"`

	ShiftStartAt *StatInkTime `json:"shift_start_at,omitempty"`

	StartAt *StatInkTime `json:"start_at,omitempty"`

	EndAt *interface{} `json:"end_at,omitempty"`

	RegisterAt *StatInkTime `json:"register_at,omitempty"`
}
