/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type StatInkGachi struct {
	Battles int32 `json:"battles,omitempty"`

	WinPct float64 `json:"win_pct,omitempty"`

	KillRatio float64 `json:"kill_ratio,omitempty"`

	KillTotal int32 `json:"kill_total,omitempty"`

	KillAvg float64 `json:"kill_avg,omitempty"`

	KillPerMin float64 `json:"kill_per_min,omitempty"`

	DeathTotal int32 `json:"death_total,omitempty"`

	DeathAvg float64 `json:"death_avg,omitempty"`

	DeathPerMin float64 `json:"death_per_min,omitempty"`

	Rules *StatInkRules `json:"rules,omitempty"`
}
