/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type Udemae struct {
	Name string `json:"name,omitempty"`

	IsX bool `json:"is_x,omitempty"`

	IsNumberReached bool `json:"is_number_reached,omitempty"`

	Number int32 `json:"number,omitempty"`

	SPlusNumber int32 `json:"s_plus_number,omitempty"`
}
