/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type SplatnetShift struct {
	DangerRate float64 `json:"danger_rate,omitempty"`

	JobResult *SplatnetJobResult `json:"job_result,omitempty"`

	JobScore int32 `json:"job_score,omitempty"`

	JobRate int32 `json:"job_rate,omitempty"`

	GradePoint int32 `json:"grade_point,omitempty"`

	GradePointDelta int32 `json:"grade_point_delta,omitempty"`

	OtherResults []SplatnetShiftPlayer `json:"other_results,omitempty"`

	KumaPoint int32 `json:"kuma_point,omitempty"`

	StartTime int32 `json:"start_time,omitempty"`

	PlayerType *PlayerType `json:"player_type,omitempty"`

	PlayTime int32 `json:"play_time,omitempty"`

	BossCounts *BossCounts `json:"boss_counts,omitempty"`

	EndTime int32 `json:"end_time,omitempty"`

	MyResult *SplatnetShiftPlayer `json:"my_result,omitempty"`

	WaveDetails []Wave `json:"wave_details,omitempty"`

	Grade *Grade `json:"grade,omitempty"`

	Schedule *Schedule `json:"schedule,omitempty"`
}
