/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type Brand struct {
	Id string `json:"id,omitempty"`

	Image string `json:"image,omitempty"`

	Name string `json:"name,omitempty"`

	FrequentSkill *SplatnetTriple `json:"frequent_skill,omitempty"`
}
