/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type StatInkShiftStats struct {
	WorkCount int32 `json:"work_count,omitempty"`

	TotalGoldenEggs int32 `json:"total_golden_eggs,omitempty"`

	TotalEggs int32 `json:"total_eggs,omitempty"`

	TotalRescued int32 `json:"total_rescued,omitempty"`

	TotalPoint int32 `json:"total_point,omitempty"`

	AsOf *StatInkTime `json:"as_of,omitempty"`

	RegisteredAt *StatInkTime `json:"registered_at,omitempty"`
}
