/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type salmonWeaponScheduleEnum string

// List of salmonWeaponScheduleEnum
const (
	RANDOM_GRIZZCO_SCHEDULE      salmonWeaponScheduleEnum = "Random Grizzco"
	RANDOM_SCHEDULE              salmonWeaponScheduleEnum = "Random"
	SPLOOSH_O_MATIC_SCHEDULE     salmonWeaponScheduleEnum = "Sploosh-o-matic"
	SPLATTERSHOT_JR_SCHEDULE     salmonWeaponScheduleEnum = "Splattershot Jr."
	SPLASH_O_MATIC_SCHEDULE      salmonWeaponScheduleEnum = "Splash-o-matic"
	AEROSPRAY_MG_SCHEDULE        salmonWeaponScheduleEnum = "Aerospray MG"
	SPLATTERSHOT_SCHEDULE        salmonWeaponScheduleEnum = "Splattershot"
	five2GAL_SCHEDULE            salmonWeaponScheduleEnum = ".52 Gal"
	N_ZAP_85_SCHEDULE            salmonWeaponScheduleEnum = "N-ZAP '85"
	SPLATTERSHOT_PRO_SCHEDULE    salmonWeaponScheduleEnum = "Splattershot Pro"
	nine6GAL_SCHEDULE            salmonWeaponScheduleEnum = ".96 Gal"
	JET_SQUELCHER_SCHEDULE       salmonWeaponScheduleEnum = "Jet Squelcher"
	LUNA_BLASTER_SCHEDULE        salmonWeaponScheduleEnum = "Luna Blaster"
	BLASTER_SCHEDULE             salmonWeaponScheduleEnum = "Blaster"
	RANGE_BLASTER_SCHEDULE       salmonWeaponScheduleEnum = "Range Blaster"
	CLASH_BLASTER_SCHEDULE       salmonWeaponScheduleEnum = "Clash Blaster"
	RAPID_BLASTER_SCHEDULE       salmonWeaponScheduleEnum = "Rapid Blaster"
	RAPID_BLASTER_PRO_SCHEDULE   salmonWeaponScheduleEnum = "Rapid Blaster Pro"
	L_3_NOZZLENOSE_SCHEDULE      salmonWeaponScheduleEnum = "L-3 Nozzlenose"
	H_3_NOZZLENOSE_SCHEDULE      salmonWeaponScheduleEnum = "H-3 Nozzlenose"
	SQUEEZER_SCHEDULE            salmonWeaponScheduleEnum = "Squeezer"
	CARBON_ROLLER_SCHEDULE       salmonWeaponScheduleEnum = "Carbon Roller"
	SPLAT_ROLLER_SCHEDULE        salmonWeaponScheduleEnum = "Splat Roller"
	DYNAMO_ROLLER_SCHEDULE       salmonWeaponScheduleEnum = "Dynamo Roller"
	FLINGZA_ROLLER_SCHEDULE      salmonWeaponScheduleEnum = "Flingza Roller"
	INKBRUSH_SCHEDULE            salmonWeaponScheduleEnum = "Inkbrush"
	OCTOBRUSH_SCHEDULE           salmonWeaponScheduleEnum = "Octobrush"
	CLASSIC_SQUIFFER_SCHEDULE    salmonWeaponScheduleEnum = "Classic Squiffer"
	SPLAT_CHARGER_SCHEDULE       salmonWeaponScheduleEnum = "Splat Charger"
	SPLATTERSCOPE_SCHEDULE       salmonWeaponScheduleEnum = "Splatterscope"
	E_LITER_4_K_SCHEDULE         salmonWeaponScheduleEnum = "E-liter 4K"
	E_LITER_4_K_SCOPE_SCHEDULE   salmonWeaponScheduleEnum = "E-liter 4K Scope"
	BAMBOOZLER_14_MK_I_SCHEDULE  salmonWeaponScheduleEnum = "Bamboozler 14 Mk I"
	GOO_TUBER_SCHEDULE           salmonWeaponScheduleEnum = "Goo Tuber"
	SLOSHER_SCHEDULE             salmonWeaponScheduleEnum = "Slosher"
	SODA_SLOSHER_SCHEDULE        salmonWeaponScheduleEnum = "Soda Slosher"
	TRI_SLOSHER_SCHEDULE         salmonWeaponScheduleEnum = "Tri-Slosher"
	SLOSHING_MACHINE_SCHEDULE    salmonWeaponScheduleEnum = "Sloshing Machine"
	BLOBLOBBER_SCHEDULE          salmonWeaponScheduleEnum = "Bloblobber"
	EXPLOSHER_SCHEDULE           salmonWeaponScheduleEnum = "Explosher"
	MINI_SPLATLING_SCHEDULE      salmonWeaponScheduleEnum = "Mini Splatling"
	HEAVY_SPLATLING_SCHEDULE     salmonWeaponScheduleEnum = "Heavy Splatling"
	HYDRA_SPLATLING_SCHEDULE     salmonWeaponScheduleEnum = "Hydra Splatling"
	BALLPOINT_SPLATLING_SCHEDULE salmonWeaponScheduleEnum = "Ballpoint Splatling"
	NAUTILUS_47_SCHEDULE         salmonWeaponScheduleEnum = "Nautilus 47"
	DAPPLE_DUALIES_SCHEDULE      salmonWeaponScheduleEnum = "Dapple Dualies"
	SPLAT_DUALIES_SCHEDULE       salmonWeaponScheduleEnum = "Splat Dualies"
	GLOOGA_DUALIES_SCHEDULE      salmonWeaponScheduleEnum = "Glooga Dualies"
	DUALIE_SQUELCHERS_SCHEDULE   salmonWeaponScheduleEnum = "Dualie Squelchers"
	DARK_TETRA_DUALIES_SCHEDULE  salmonWeaponScheduleEnum = "Dark Tetra Dualies"
	SPLAT_BRELLA_SCHEDULE        salmonWeaponScheduleEnum = "Splat Brella"
	TENTA_BRELLA_SCHEDULE        salmonWeaponScheduleEnum = "Tenta Brella"
	UNDERCOVER_BRELLA_SCHEDULE   salmonWeaponScheduleEnum = "Undercover Brella"
)
