/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type StatInkShiftUser struct {
	Id int32 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	ScreenName string `json:"screen_name,omitempty"`

	Url string `json:"url,omitempty"`

	SalmonUrl string `json:"salmon_url,omitempty"`

	BattleUrl string `json:"battle_url,omitempty"`

	JoinAt *StatInkTime `json:"join_at,omitempty"`

	Profile *StatInkProfile `json:"profile,omitempty"`

	Stats *StatInkShiftStats `json:"stats,omitempty"`
}
