/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

import (
	"time"
)

type StatInkTime struct {
	Time int32 `json:"time,omitempty"`

	Iso8601 time.Time `json:"iso8601,omitempty"`
}
