/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type SplatnetQuad struct {
	Id string `json:"id,omitempty"`

	ImageA string `json:"image_a,omitempty"`

	ImageB string `json:"image_b,omitempty"`

	Name string `json:"name,omitempty"`
}
