/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type BattleSplatnet struct {
	Udemae *Udemae `json:"udemae,omitempty"`

	Stage *SplatnetTriple `json:"stage,omitempty"`

	OtherTeamCount int32 `json:"other_team_count,omitempty"`

	MyTeamCount int32 `json:"my_team_count,omitempty"`

	StarRank int32 `json:"star_rank,omitempty"`

	Rule *Rule `json:"rule,omitempty"`

	PlayerResult *PlayerResult `json:"player_result,omitempty"`

	EstimateGachiPower int32 `json:"estimate_gachi_power,omitempty"`

	ElapsedTime int32 `json:"elapsed_time,omitempty"`

	StartTime int32 `json:"start_time,omitempty"`

	GameMode *SplatnetDouble `json:"game_mode,omitempty"`

	XPower *interface{} `json:"x_power,omitempty"`

	BattleNumber string `json:"battle_number,omitempty"`

	Type_ string `json:"type,omitempty"`

	PlayerRank int32 `json:"player_rank,omitempty"`

	CrownPlayers *interface{} `json:"crown_players,omitempty"`

	MyTeamMembers []PlayerResult `json:"my_team_members,omitempty"`

	OtherTeamMembers []PlayerResult `json:"other_team_members,omitempty"`

	WeaponPaintPoint int32 `json:"weapon_paint_point,omitempty"`

	Rank *interface{} `json:"rank,omitempty"`

	MyTeamResult *SplatnetDouble `json:"my_team_result,omitempty"`

	EstimateXPower *interface{} `json:"estimate_x_power,omitempty"`

	OtherTeamResult *SplatnetDouble `json:"other_team_result,omitempty"`

	LeaguePoint float64 `json:"league_point,omitempty"`

	WinMeter float64 `json:"win_meter,omitempty"`

	MyTeamPercentage float64 `json:"my_team_percentage,omitempty"`

	OtherTeamPercentage float64 `json:"other_team_percentage,omitempty"`

	TagId string `json:"tag_id,omitempty"`
}
