/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type StatInkRules struct {
	Area *StatInkRulesSub `json:"area,omitempty"`

	Yagura *StatInkRulesSub `json:"yagura,omitempty"`

	Hoko *StatInkRulesSub `json:"hoko,omitempty"`

	Asari *StatInkRulesSub `json:"asari,omitempty"`
}
