/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type StatInkName struct {
	DeDE string `json:"de_DE,omitempty"`

	EnGB string `json:"en_GB,omitempty"`

	EnUS string `json:"en_US,omitempty"`

	EsES string `json:"es_ES,omitempty"`

	EsMX string `json:"es_MX,omitempty"`

	FrCA string `json:"fr_CA,omitempty"`

	FrFR string `json:"fr_FR,omitempty"`

	ItIT string `json:"it_IT,omitempty"`

	JaJP string `json:"ja_JP,omitempty"`

	NlNL string `json:"nl_NL,omitempty"`

	RuRU string `json:"ru_RU,omitempty"`

	ZhCN string `json:"zh_CN,omitempty"`

	ZhTW string `json:"zh_TW,omitempty"`
}
