/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type SplatnetShiftPlayer struct {
	SpecialCounts []int32 `json:"special_counts,omitempty"`

	Special *SplatnetQuad `json:"special,omitempty"`

	Pid string `json:"pid,omitempty"`

	PlayerType *PlayerType `json:"player_type,omitempty"`

	WeaponList []WeaponList `json:"weapon_list,omitempty"`

	Name string `json:"name,omitempty"`

	DeadCount int32 `json:"dead_count,omitempty"`

	GoldenIkuraNum int32 `json:"golden_ikura_num,omitempty"`

	BossKillCounts *BossCounts `json:"boss_kill_counts,omitempty"`

	IkuraNum int32 `json:"ikura_num,omitempty"`

	HelpCount int32 `json:"help_count,omitempty"`
}
