/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type StatInkClothes struct {
	Gear *StatInkGear `json:"gear,omitempty"`

	PrimaryAbility *StatInkKeyName `json:"primary_ability,omitempty"`

	SecondaryAbilities []StatInkKeyName `json:"secondary_abilities,omitempty"`
}
