/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type Schedule struct {
	StartTime int32 `json:"start_time,omitempty"`

	Weapons []WeaponList `json:"weapons,omitempty"`

	EndTime int32 `json:"end_time,omitempty"`

	Stage *Stage `json:"stage,omitempty"`
}
