/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type StatInkWeapon struct {
	Key string `json:"key,omitempty"`

	Name *StatInkName `json:"name,omitempty"`

	Splatnet int32 `json:"splatnet,omitempty"`

	Type_ *StatInkWeaponType `json:"type,omitempty"`

	ReskinOf string `json:"reskin_of,omitempty"`

	MainRef string `json:"main_ref,omitempty"`

	Sub *StatInkKeyName `json:"sub,omitempty"`

	Special *StatInkKeyName `json:"special,omitempty"`

	MainPowerUp *StatInkKeyName `json:"main_power_up,omitempty"`
}
