/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type StatInkAgent struct {
	Name string `json:"name,omitempty"`

	Version string `json:"version,omitempty"`

	GameVersion *interface{} `json:"game_version,omitempty"`

	GameVersionDate *interface{} `json:"game_version_date,omitempty"`

	Custom *interface{} `json:"custom,omitempty"`

	Variables *AllOfstatInkAgentVariables `json:"variables,omitempty"`
}
