/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type BossCounts struct {
	Var3 *Boss `json:"3,omitempty"`

	Var6 *Boss `json:"6,omitempty"`

	Var9 *Boss `json:"9,omitempty"`

	Var12 *Boss `json:"12,omitempty"`

	Var13 *Boss `json:"13,omitempty"`

	Var14 *Boss `json:"14,omitempty"`

	Var15 *Boss `json:"15,omitempty"`

	Var16 *Boss `json:"16,omitempty"`

	Var21 *Boss `json:"21,omitempty"`
}
