/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_code

type StatInkFreshness struct {
	Freshness float64 `json:"freshness,omitempty"`

	Title *StatInkName `json:"title,omitempty"`
}
