package db_objects

import (
	"github.com/cass-dlcm/SplatStatsGo/enums"
)

type Battle struct {
	UserId                  int64
	SplatnetJson            *int64                  `json:"splatnet_json,omitempty"` // Links to battleSplatnet
	SplatnetUpload          int8                    `json:"splatnet_upload"`
	StatInkJson             *int64                  `json:"stat_ink_json,omitempty"` // Links to battleStatInk
	StatInkUpload           int8                    `json:"stat_ink_upload"`
	SplatnetNumber          int64                   `json:"splatnet_number"`
	PlayerSplatnetId        string                  `json:"player_splatnet_id"`
	ElapsedTime             int                     `json:"elapsed_time"`
	HasDisconnectedPlayer   int8                    `json:"has_disconnected_player"`
	LeaguePoint             *float64                `json:"league_point,omitempty"`
	MatchType               enums.Lobby             `json:"match_type"`
	Rule                    enums.Rule              `json:"rule"`
	MyTeamCount             float64                 `json:"my_team_count,omitempty"`
	OtherTeamCount          float64                 `json:"other_team_count,omitempty"`
	SplatfestPoint          *float64                `json:"splatfest_point,omitempty"`
	SplatfestTitle          *string                 `json:"splatfest_title,omitempty"`
	Stage                   enums.BattleStage       `json:"stage,omitempty"`
	TagId                   *string                 `json:"tag_id,omitempty"`
	Time                    int                     `json:"time,omitempty"`
	Win                     int8                    `json:"win,omitempty"`
	WinMeter                *float64                `json:"win_meter,omitempty"`
	Opponent0SplatnetId     *string                 `json:"opponent0_splatnet_id,omitempty"`
	Opponent0Name           *string                 `json:"opponent0_name,omitempty"`
	Opponent0Rank           *string                 `json:"opponent0_rank,omitempty"`
	Opponent0LevelStar      *int                    `json:"opponent0_level_star,omitempty"`
	Opponent0Level          *int                    `json:"opponent0_level,omitempty"`
	Opponent0Weapon         *enums.BattleWeaponEnum `json:"opponent0_weapon,omitempty"`
	Opponent0Gender         *enums.GenderEnum       `json:"opponent0_gender,omitempty"`
	Opponent0Species        *enums.SpeciesEnum      `json:"opponent0_species,omitempty"`
	Opponent0Assists        *int                    `json:"opponent0_assists,omitempty"`
	Opponent0Deaths         *int                    `json:"opponent0_deaths,omitempty"`
	Opponent0GamePaintPoint *int                    `json:"opponent0_game_paint_point,omitempty"`
	Opponent0Kills          *int                    `json:"opponent0_kills,omitempty"`
	Opponent0Specials       *int                    `json:"opponent0_specials,omitempty"`
	Opponent0Headgear       *string                 `json:"opponent0_headgear,omitempty"`
	Opponent0HeadgearMain   *string                 `json:"opponent0_headgear_main,omitempty"`
	Opponent0HeadgearSub0   *string                 `json:"opponent0_headgear_sub0,omitempty"`
	Opponent0HeadgearSub1   *string                 `json:"opponent0_headgear_sub1,omitempty"`
	Opponent0HeadgearSub2   *string                 `json:"opponent0_headgear_sub2,omitempty"`
	Opponent0Clothes        *string                 `json:"opponent0_clothes,omitempty"`
	Opponent0ClothesMain    *string                 `json:"opponent0_clothes_main,omitempty"`
	Opponent0ClothesSub0    *string                 `json:"opponent0_clothes_sub0,omitempty"`
	Opponent0ClothesSub1    *string                 `json:"opponent0_clothes_sub1,omitempty"`
	Opponent0ClothesSub2    *string                 `json:"opponent0_clothes_sub2,omitempty"`
	Opponent0Shoes          *string                 `json:"opponent0_shoes,omitempty"`
	Opponent0ShoesMain      *string                 `json:"opponent0_shoes_main,omitempty"`
	Opponent0ShoesSub0      *string                 `json:"opponent0_shoes_sub0,omitempty"`
	Opponent0ShoesSub1      *string                 `json:"opponent0_shoes_sub1,omitempty"`
	Opponent0ShoesSub2      *string                 `json:"opponent0_shoes_sub2,omitempty"`
	Opponent1SplatnetId     *string                 `json:"opponent1_splatnet_id,omitempty"`
	Opponent1Name           *string                 `json:"opponent1_name,omitempty"`
	Opponent1Rank           *string                 `json:"opponent1_rank,omitempty"`
	Opponent1LevelStar      *int                    `json:"opponent1_level_star,omitempty"`
	Opponent1Level          *int                    `json:"opponent1_level,omitempty"`
	Opponent1Weapon         *enums.BattleWeaponEnum `json:"opponent1_weapon,omitempty"`
	Opponent1Gender         *enums.GenderEnum       `json:"opponent1_gender,omitempty"`
	Opponent1Species        *enums.SpeciesEnum      `json:"opponent1_species,omitempty"`
	Opponent1Assists        *int                    `json:"opponent1_assists,omitempty"`
	Opponent1Deaths         *int                    `json:"opponent1_deaths,omitempty"`
	Opponent1GamePaintPoint *int                    `json:"opponent1_game_paint_point,omitempty"`
	Opponent1Kills          *int                    `json:"opponent1_kills,omitempty"`
	Opponent1Specials       *int                    `json:"opponent1_specials,omitempty"`
	Opponent1Headgear       *string                 `json:"opponent1_headgear,omitempty"`
	Opponent1HeadgearMain   *string                 `json:"opponent1_headgear_main,omitempty"`
	Opponent1HeadgearSub0   *string                 `json:"opponent1_headgear_sub0,omitempty"`
	Opponent1HeadgearSub1   *string                 `json:"opponent1_headgear_sub1,omitempty"`
	Opponent1HeadgearSub2   *string                 `json:"opponent1_headgear_sub2,omitempty"`
	Opponent1Clothes        *string                 `json:"opponent1_clothes,omitempty"`
	Opponent1ClothesMain    *string                 `json:"opponent1_clothes_main,omitempty"`
	Opponent1ClothesSub0    *string                 `json:"opponent1_clothes_sub0,omitempty"`
	Opponent1ClothesSub1    *string                 `json:"opponent1_clothes_sub1,omitempty"`
	Opponent1ClothesSub2    *string                 `json:"opponent1_clothes_sub2,omitempty"`
	Opponent1Shoes          *string                 `json:"opponent1_shoes,omitempty"`
	Opponent1ShoesMain      *string                 `json:"opponent1_shoes_main,omitempty"`
	Opponent1ShoesSub0      *string                 `json:"opponent1_shoes_sub0,omitempty"`
	Opponent1ShoesSub1      *string                 `json:"opponent1_shoes_sub1,omitempty"`
	Opponent1ShoesSub2      *string                 `json:"opponent1_shoes_sub2,omitempty"`
	Opponent2SplatnetId     *string                 `json:"opponent2_splatnet_id,omitempty"`
	Opponent2Name           *string                 `json:"opponent2_name,omitempty"`
	Opponent2Rank           *string                 `json:"opponent2_rank,omitempty"`
	Opponent2LevelStar      *int                    `json:"opponent2_level_star,omitempty"`
	Opponent2Level          *int                    `json:"opponent2_level,omitempty"`
	Opponent2Weapon         *enums.BattleWeaponEnum `json:"opponent2_weapon,omitempty"`
	Opponent2Gender         *enums.GenderEnum       `json:"opponent2_gender,omitempty"`
	Opponent2Species        *enums.SpeciesEnum      `json:"opponent2_species,omitempty"`
	Opponent2Assists        *int                    `json:"opponent2_assists,omitempty"`
	Opponent2Deaths         *int                    `json:"opponent2_deaths,omitempty"`
	Opponent2GamePaintPoint *int                    `json:"opponent2_game_paint_point,omitempty"`
	Opponent2Kills          *int                    `json:"opponent2_kills,omitempty"`
	Opponent2Specials       *int                    `json:"opponent2_specials,omitempty"`
	Opponent2Headgear       *string                 `json:"opponent2_headgear,omitempty"`
	Opponent2HeadgearMain   *string                 `json:"opponent2_headgear_main,omitempty"`
	Opponent2HeadgearSub0   *string                 `json:"opponent2_headgear_sub0,omitempty"`
	Opponent2HeadgearSub1   *string                 `json:"opponent2_headgear_sub1,omitempty"`
	Opponent2HeadgearSub2   *string                 `json:"opponent2_headgear_sub2,omitempty"`
	Opponent2Clothes        *string                 `json:"opponent2_clothes,omitempty"`
	Opponent2ClothesMain    *string                 `json:"opponent2_clothes_main,omitempty"`
	Opponent2ClothesSub0    *string                 `json:"opponent2_clothes_sub0,omitempty"`
	Opponent2ClothesSub1    *string                 `json:"opponent2_clothes_sub1,omitempty"`
	Opponent2ClothesSub2    *string                 `json:"opponent2_clothes_sub2,omitempty"`
	Opponent2Shoes          *string                 `json:"opponent2_shoes,omitempty"`
	Opponent2ShoesMain      *string                 `json:"opponent2_shoes_main,omitempty"`
	Opponent2ShoesSub0      *string                 `json:"opponent2_shoes_sub0,omitempty"`
	Opponent2ShoesSub1      *string                 `json:"opponent2_shoes_sub1,omitempty"`
	Opponent2ShoesSub2      *string                 `json:"opponent2_shoes_sub2,omitempty"`
	Opponent3SplatnetId     *string                 `json:"opponent3_splatnet_id,omitempty"`
	Opponent3Name           *string                 `json:"opponent3_name,omitempty"`
	Opponent3Rank           *string                 `json:"opponent3_rank,omitempty"`
	Opponent3LevelStar      *int                    `json:"opponent3_level_star,omitempty"`
	Opponent3Level          *int                    `json:"opponent3_level,omitempty"`
	Opponent3Weapon         *enums.BattleWeaponEnum `json:"opponent3_weapon,omitempty"`
	Opponent3Gender         *enums.GenderEnum       `json:"opponent3_gender,omitempty"`
	Opponent3Species        *enums.SpeciesEnum      `json:"opponent3_species,omitempty"`
	Opponent3Assists        *int                    `json:"opponent3_assists,omitempty"`
	Opponent3Deaths         *int                    `json:"opponent3_deaths,omitempty"`
	Opponent3GamePaintPoint *int                    `json:"opponent3_game_paint_point,omitempty"`
	Opponent3Kills          *int                    `json:"opponent3_kills,omitempty"`
	Opponent3Specials       *int                    `json:"opponent3_specials,omitempty"`
	Opponent3Headgear       *string                 `json:"opponent3_headgear,omitempty"`
	Opponent3HeadgearMain   *string                 `json:"opponent3_headgear_main,omitempty"`
	Opponent3HeadgearSub0   *string                 `json:"opponent3_headgear_sub0,omitempty"`
	Opponent3HeadgearSub1   *string                 `json:"opponent3_headgear_sub1,omitempty"`
	Opponent3HeadgearSub2   *string                 `json:"opponent3_headgear_sub2,omitempty"`
	Opponent3Clothes        *string                 `json:"opponent3_clothes,omitempty"`
	Opponent3ClothesMain    *string                 `json:"opponent3_clothes_main,omitempty"`
	Opponent3ClothesSub0    *string                 `json:"opponent3_clothes_sub0,omitempty"`
	Opponent3ClothesSub1    *string                 `json:"opponent3_clothes_sub1,omitempty"`
	Opponent3ClothesSub2    *string                 `json:"opponent3_clothes_sub2,omitempty"`
	Opponent3Shoes          *string                 `json:"opponent3_shoes,omitempty"`
	Opponent3ShoesMain      *string                 `json:"opponent3_shoes_main,omitempty"`
	Opponent3ShoesSub0      *string                 `json:"opponent3_shoes_sub0,omitempty"`
	Opponent3ShoesSub1      *string                 `json:"opponent3_shoes_sub1,omitempty"`
	Opponent3ShoesSub2      *string                 `json:"opponent3_shoes_sub2,omitempty"`
	Teammate0SplatnetId     *string                 `json:"teammate0_splatnet_id,omitempty"`
	Teammate0Name           *string                 `json:"teammate0_name,omitempty"`
	Teammate0Rank           *string                 `json:"teammate0_rank,omitempty"`
	Teammate0LevelStar      *int                    `json:"teammate0_level_star,omitempty"`
	Teammate0Level          *int                    `json:"teammate0_level,omitempty"`
	Teammate0Weapon         *enums.BattleWeaponEnum `json:"teammate0_weapon,omitempty"`
	Teammate0Gender         *enums.GenderEnum       `json:"teammate0_gender,omitempty"`
	Teammate0Species        *enums.SpeciesEnum      `json:"teammate0_species,omitempty"`
	Teammate0Assists        *int                    `json:"teammate0_assists,omitempty"`
	Teammate0Deaths         *int                    `json:"teammate0_deaths,omitempty"`
	Teammate0GamePaintPoint *int                    `json:"teammate0_game_paint_point,omitempty"`
	Teammate0Kills          *int                    `json:"teammate0_kills,omitempty"`
	Teammate0Specials       *int                    `json:"teammate0_specials,omitempty"`
	Teammate0Headgear       *string                 `json:"teammate0_headgear,omitempty"`
	Teammate0HeadgearMain   *string                 `json:"teammate0_headgear_main,omitempty"`
	Teammate0HeadgearSub0   *string                 `json:"teammate0_headgear_sub0,omitempty"`
	Teammate0HeadgearSub1   *string                 `json:"teammate0_headgear_sub1,omitempty"`
	Teammate0HeadgearSub2   *string                 `json:"teammate0_headgear_sub2,omitempty"`
	Teammate0Clothes        *string                 `json:"teammate0_clothes,omitempty"`
	Teammate0ClothesMain    *string                 `json:"teammate0_clothes_main,omitempty"`
	Teammate0ClothesSub0    *string                 `json:"teammate0_clothes_sub0,omitempty"`
	Teammate0ClothesSub1    *string                 `json:"teammate0_clothes_sub1,omitempty"`
	Teammate0ClothesSub2    *string                 `json:"teammate0_clothes_sub2,omitempty"`
	Teammate0Shoes          *string                 `json:"teammate0_shoes,omitempty"`
	Teammate0ShoesMain      *string                 `json:"teammate0_shoes_main,omitempty"`
	Teammate0ShoesSub0      *string                 `json:"teammate0_shoes_sub0,omitempty"`
	Teammate0ShoesSub1      *string                 `json:"teammate0_shoes_sub1,omitempty"`
	Teammate0ShoesSub2      *string                 `json:"teammate0_shoes_sub2,omitempty"`
	Teammate1SplatnetId     *string                 `json:"teammate1_splatnet_id,omitempty"`
	Teammate1Name           *string                 `json:"teammate1_name,omitempty"`
	Teammate1Rank           *string                 `json:"teammate1_rank,omitempty"`
	Teammate1LevelStar      *int                    `json:"teammate1_level_star,omitempty"`
	Teammate1Level          *int                    `json:"teammate1_level,omitempty"`
	Teammate1Weapon         *enums.BattleWeaponEnum `json:"teammate1_weapon,omitempty"`
	Teammate1Gender         *enums.GenderEnum       `json:"teammate1_gender,omitempty"`
	Teammate1Species        *enums.SpeciesEnum      `json:"teammate1_species,omitempty"`
	Teammate1Assists        *int                    `json:"teammate1_assists,omitempty"`
	Teammate1Deaths         *int                    `json:"teammate1_deaths,omitempty"`
	Teammate1GamePaintPoint *int                    `json:"teammate1_game_paint_point,omitempty"`
	Teammate1Kills          *int                    `json:"teammate1_kills,omitempty"`
	Teammate1Specials       *int                    `json:"teammate1_specials,omitempty"`
	Teammate1Headgear       *string                 `json:"teammate1_headgear,omitempty"`
	Teammate1HeadgearMain   *string                 `json:"teammate1_headgear_main,omitempty"`
	Teammate1HeadgearSub0   *string                 `json:"teammate1_headgear_sub0,omitempty"`
	Teammate1HeadgearSub1   *string                 `json:"teammate1_headgear_sub1,omitempty"`
	Teammate1HeadgearSub2   *string                 `json:"teammate1_headgear_sub2,omitempty"`
	Teammate1Clothes        *string                 `json:"teammate1_clothes,omitempty"`
	Teammate1ClothesMain    *string                 `json:"teammate1_clothes_main,omitempty"`
	Teammate1ClothesSub0    *string                 `json:"teammate1_clothes_sub0,omitempty"`
	Teammate1ClothesSub1    *string                 `json:"teammate1_clothes_sub1,omitempty"`
	Teammate1ClothesSub2    *string                 `json:"teammate1_clothes_sub2,omitempty"`
	Teammate1Shoes          *string                 `json:"teammate1_shoes,omitempty"`
	Teammate1ShoesMain      *string                 `json:"teammate1_shoes_main,omitempty"`
	Teammate1ShoesSub0      *string                 `json:"teammate1_shoes_sub0,omitempty"`
	Teammate1ShoesSub1      *string                 `json:"teammate1_shoes_sub1,omitempty"`
	Teammate1ShoesSub2      *string                 `json:"teammate1_shoes_sub2,omitempty"`
	Teammate2SplatnetId     *string                 `json:"teammate2_splatnet_id,omitempty"`
	Teammate2Name           *string                 `json:"teammate2_name,omitempty"`
	Teammate2Rank           *string                 `json:"teammate2_rank,omitempty"`
	Teammate2LevelStar      *int                    `json:"teammate2_level_star,omitempty"`
	Teammate2Level          *int                    `json:"teammate2_level,omitempty"`
	Teammate2Weapon         *enums.BattleWeaponEnum `json:"teammate2_weapon,omitempty"`
	Teammate2Gender         *enums.GenderEnum       `json:"teammate2_gender,omitempty"`
	Teammate2Species        *enums.SpeciesEnum      `json:"teammate2_species,omitempty"`
	Teammate2Assists        *int                    `json:"teammate2_assists,omitempty"`
	Teammate2Deaths         *int                    `json:"teammate2_deaths,omitempty"`
	Teammate2GamePaintPoint *int                    `json:"teammate2_game_paint_point,omitempty"`
	Teammate2Kills          *int                    `json:"teammate2_kills,omitempty"`
	Teammate2Specials       *int                    `json:"teammate2_specials,omitempty"`
	Teammate2Headgear       *string                 `json:"teammate2_headgear,omitempty"`
	Teammate2HeadgearMain   *string                 `json:"teammate2_headgear_main,omitempty"`
	Teammate2HeadgearSub0   *string                 `json:"teammate2_headgear_sub0,omitempty"`
	Teammate2HeadgearSub1   *string                 `json:"teammate2_headgear_sub1,omitempty"`
	Teammate2HeadgearSub2   *string                 `json:"teammate2_headgear_sub2,omitempty"`
	Teammate2Clothes        *string                 `json:"teammate2_clothes,omitempty"`
	Teammate2ClothesMain    *string                 `json:"teammate2_clothes_main,omitempty"`
	Teammate2ClothesSub0    *string                 `json:"teammate2_clothes_sub0,omitempty"`
	Teammate2ClothesSub1    *string                 `json:"teammate2_clothes_sub1,omitempty"`
	Teammate2ClothesSub2    *string                 `json:"teammate2_clothes_sub2,omitempty"`
	Teammate2Shoes          *string                 `json:"teammate2_shoes,omitempty"`
	Teammate2ShoesMain      *string                 `json:"teammate2_shoes_main,omitempty"`
	Teammate2ShoesSub0      *string                 `json:"teammate2_shoes_sub0,omitempty"`
	Teammate2ShoesSub1      *string                 `json:"teammate2_shoes_sub1,omitempty"`
	Teammate2ShoesSub2      *string                 `json:"teammate2_shoes_sub2,omitempty"`
	PlayerName              string                  `json:"player_name,omitempty"`
	PlayerRank              *string                 `json:"player_rank,omitempty"`
	PlayerLevelStar         int                     `json:"player_level_star,omitempty"`
	PlayerLevel             int                     `json:"player_level,omitempty"`
	PlayerWeapon            enums.BattleWeaponEnum  `json:"player_weapon,omitempty"`
	PlayerGender            enums.GenderEnum        `json:"player_gender,omitempty"`
	PlayerSpecies           enums.SpeciesEnum       `json:"player_species,omitempty"`
	PlayerAssists           int                     `json:"player_assists,omitempty"`
	PlayerDeaths            int                     `json:"player_deaths,omitempty"`
	PlayerGamePaintPoint    int                     `json:"player_game_paint_point,omitempty"`
	PlayerKills             int                     `json:"player_kills,omitempty"`
	PlayerSpecials          int                     `json:"player_specials,omitempty"`
	PlayerHeadgear          string                  `json:"player_headgear,omitempty"`
	PlayerHeadgearMain      string                  `json:"player_headgear_main,omitempty"`
	PlayerHeadgearSub0      *string                 `json:"player_headgear_sub0,omitempty"`
	PlayerHeadgearSub1      *string                 `json:"player_headgear_sub1,omitempty"`
	PlayerHeadgearSub2      *string                 `json:"player_headgear_sub2,omitempty"`
	PlayerClothes           string                  `json:"player_clothes,omitempty"`
	PlayerClothesMain       string                  `json:"player_clothes_main,omitempty"`
	PlayerClothesSub0       *string                 `json:"player_clothes_sub0,omitempty"`
	PlayerClothesSub1       *string                 `json:"player_clothes_sub1,omitempty"`
	PlayerClothesSub2       *string                 `json:"player_clothes_sub2,omitempty"`
	PlayerShoes             string                  `json:"player_shoes,omitempty"`
	PlayerShoesMain         string                  `json:"player_shoes_main,omitempty"`
	PlayerShoesSub0         *string                 `json:"player_shoes_sub0,omitempty"`
	PlayerShoesSub1         *string                 `json:"player_shoes_sub1,omitempty"`
	PlayerShoesSub2         *string                 `json:"player_shoes_sub2,omitempty"`
}
