/*
 * SplatStats
 *
 * This is the API documentation for a future revision of SplatStats.
 *
 * API version: 0.4.0
 * Contact: splatstats@cass-dlcm.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api_objects

import "github.com/cass-dlcm/SplatStatsGo/enums"

type SplatnetPlayerType struct {
	Gender  enums.GenderEnum  `json:"style,omitempty"`
	Species enums.SpeciesEnum `json:"species,omitempty"`
}

type SplatnetDouble struct {
	Key  string `json:"key"`
	Name string `json:"name"`
}

type SplatnetQuad struct {
	Id     string `json:"id"`
	ImageA string `json:"image_a"`
	ImageB string `json:"image_b"`
	Name   string `json:"name"`
}
